METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0003
  milestones: [10,20]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 30
  early_stop: 10
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 207
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    nid_embedding_dim : 24
    col_embedding_dim: 80
    feed_forward_dim: 256
    num_heads: 8
    num_layers: 3
    dropout: 0.1

---
PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0001
  milestones: [8,18,28]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 50
  early_stop: 20
  use_cl: False

  model_args:
    num_nodes: 325
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    nid_embedding_dim : 24
    col_embedding_dim: 80
    feed_forward_dim: 256
    num_heads: 8
    num_layers: 3
    dropout: 0.1

---
PEMS04:
  num_nodes: 307
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0003
  milestones: [15, 30, 50]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 60
  early_stop: 20
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 307
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    nid_embedding_dim : 24
    col_embedding_dim: 80
    feed_forward_dim: 256
    num_heads: 8
    num_layers: 3
    dropout: 0.1

---
PEMS08:
  num_nodes: 170
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0015
  milestones: [25, 45, 65]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 30
  early_stop: 30
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 170
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    nid_embedding_dim : 24
    col_embedding_dim: 80
    feed_forward_dim: 256
    num_heads: 8
    num_layers: 3
    dropout: 0.1
